"""Added new table TenderOldVersion

Revision ID: 73f0b0681649
Revises: 8f1491d76a40
Create Date: 2024-09-12 17:09:37.900983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f0b0681649'
down_revision: Union[str, None] = '8f1491d76a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS service_type_old")
    op.create_table('tender_old_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenderName', sa.String(length=100), nullable=False),
    sa.Column('tenderDescription', sa.String(length=500), nullable=False),
    sa.Column('tenderServiceType', postgresql.ENUM('Construction', 'Delivery', 'Manufacture', name='service_type_old'), nullable=False),
    sa.Column('tenderId', sa.UUID(), nullable=False),
    sa.Column('tenderVersion', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['tenderId'], ['tender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_old_version')
    # ### end Alembic commands ###
