"""Added Tender

Revision ID: 8f1491d76a40
Revises: a58af71eb3ce
Create Date: 2024-09-10 21:47:32.741045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f1491d76a40'
down_revision: Union[str, None] = 'a58af71eb3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('serviceType', postgresql.ENUM('Construction', 'Delivery', 'Manufacture', name='service_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('Created', 'Published', 'Closed', name='tender_status'), nullable=False),
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender')
    # ### end Alembic commands ###
